spring.application.name=User
# C?u hình k?t n?i MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/ChessGame?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?u hình Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# Xóa hibernate.dialect vì Hibernate t? ??ng ch?n dialect phù h?p
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# C?u hình HikariCP cho UTF-8
spring.datasource.hikari.connection-init-sql=SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci

# C?u hình Jackson múi gi?
spring.jackson.time-zone=Asia/Ho_Chi_Minh
